
CREATE TABLE User(
id INT PRIMARY KEY AUTO_INCREMENT,
uname VARCHAR(255),
upwd VARCHAR(255)
)

CREATE TABLE ChatNotes(
id INT PRIMARY KEY AUTO_INCREMENT,
userid INT,
ip VARCHAR(255),
chatTime DATETIME,
note VARCHAR(255),
CONSTRAINT fk_userid FOREIGN KEY (userid) REFERENCES User(id) ON DELETE CASCADE
)

